version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine
    ports:
      - '6380:6379'

  django:
    container_name: django
    build:
      context: ./marketplace
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./marketplace:/usr/src/marketplace/
    ports:
      - '9000:8000'
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./marketplace
      dockerfile: Dockerfile
    command: python3 -m celery -A marketplace worker -l info
    volumes:
      - ./marketplace:/usr/src/marketplace/
    depends_on:
      - redis
