# Generated by Django 5.0 on 2024-02-05 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 11, 6, 19, 434185, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='item_for_car',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 11, 6, 19, 435042, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='item_for_moto',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 11, 6, 19, 435042, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='motocycle',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 11, 6, 19, 434185, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 11, 6, 19, 435986, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
    ]
