# Generated by Django 4.2.9 on 2024-02-20 05:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_user_user_django_alter_car_guarantee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("Sedan", "Седан"),
                    ("Hatchback", "Хэтчбэк"),
                    ("Pickup", "Пикап"),
                    ("Cabrio", "Кабиолет"),
                ],
                default="Sedan",
                help_text="В соответствии с техпаспортом",
                max_length=15,
                verbose_name="Тип кузова",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Red"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("gray", "Gray"),
                    ("teal", "Teal"),
                ],
                default="red",
                help_text="В соответствии с техпаспортом",
                max_length=15,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(
                blank=True,
                default="Нет описания",
                help_text="Обязательно укажите поврежения \nавтомобиля (при наличии)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="drive_type",
            field=models.CharField(
                choices=[
                    ("Front", "Переднеприводный"),
                    ("Back", "Заднеприводный"),
                    ("Full", "Полноприводный"),
                ],
                default="Front",
                max_length=15,
                verbose_name="Тип привода",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine_type",
            field=models.CharField(
                choices=[("Electricity", "Электромобиль"), ("Oil", "ДВС")],
                default="Oil",
                help_text="ДВС или электрокар",
                max_length=15,
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 20, 5, 38, 33, 461329, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="item_for_car",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 20, 5, 38, 33, 461329, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="item_for_moto",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 20, 5, 38, 33, 461329, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="motocycle",
            name="body_type",
            field=models.CharField(
                choices=[("Sport", "Спортивный"), ("Classic", "Классический")],
                default="Sport",
                help_text="В соответствии с техпаспортом",
                max_length=15,
                verbose_name="Типы",
            ),
        ),
        migrations.AlterField(
            model_name="motocycle",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Red"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("gray", "Gray"),
                    ("teal", "Teal"),
                ],
                default="red",
                help_text="В соответствии с техпаспортом",
                max_length=15,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="motocycle",
            name="description",
            field=models.TextField(
                blank=True,
                default="Нет описания",
                help_text="Обязательно укажите поврежения \nавтомобиля (при наличии)",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="motocycle",
            name="engine_type",
            field=models.CharField(
                choices=[("Electricity", "Электромобиль"), ("Oil", "ДВС")],
                default="Oil",
                help_text="ДВС или электрокар",
                max_length=15,
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AlterField(
            model_name="motocycle",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 20, 5, 38, 33, 461329, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 20, 5, 38, 33, 463329, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
    ]
