# Generated by Django 5.0 on 2024-02-28 18:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_email_alter_car_guarantee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 9, 50, 51999, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='item_for_car',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 9, 50, 52869, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='item_for_moto',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 9, 50, 52869, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='motocycle',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 9, 50, 51999, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 9, 50, 53824, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.favorite'),
        ),
    ]
