# Generated by Django 4.2.9 on 2024-03-09 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_itemforcar_itemformotorcycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='guarantee_period',
            field=models.SmallIntegerField(choices=[(6, '6 month'), (12, '12 month'), (24, '2 years'), (36, '3 years'), (60, '5 years')], default=12, verbose_name='Гарантийный период'),
        ),
        migrations.AlterField(
            model_name='car',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 9, 12, 48, 32, 346952, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='itemforcar',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 9, 12, 48, 32, 347951, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='itemformotorcycle',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 9, 12, 48, 32, 347951, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='motocycle',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 9, 12, 48, 32, 346952, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 9, 12, 48, 32, 348951, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
    ]
