# Generated by Django 5.0 on 2024-02-28 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_car_guarantee_alter_item_for_car_guarantee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='users', to='main_app.favorite'),
        ),
        migrations.AlterField(
            model_name='car',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 12, 41, 61753, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='item_for_car',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 12, 41, 62598, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='item_for_moto',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 12, 41, 62598, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='motocycle',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 12, 41, 61753, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='guarantee',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 28, 18, 12, 41, 63601, tzinfo=datetime.timezone.utc), verbose_name='Гарантийный срок'),
        ),
    ]
