# Generated by Django 4.2.9 on 2024-03-09 13:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_service_guarantee_period_alter_car_guarantee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="guarantee_period",
            field=models.SmallIntegerField(
                choices=[
                    (6, "6 месяцев"),
                    (12, "12 месяцев"),
                    (24, "2 года"),
                    (36, "3 года"),
                    (60, "5 лет"),
                ],
                default=12,
                verbose_name="Гарантийный период",
            ),
        ),
        migrations.AddField(
            model_name="motocycle",
            name="guarantee_period",
            field=models.SmallIntegerField(
                choices=[
                    (6, "6 месяцев"),
                    (12, "12 месяцев"),
                    (24, "2 года"),
                    (36, "3 года"),
                    (60, "5 лет"),
                ],
                default=12,
                verbose_name="Гарантийный период",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Красный"),
                    ("blue", "Синий"),
                    ("green", "Зеленый"),
                    ("yellow", "Желтый"),
                    ("orange", "Ораньжевый"),
                    ("purple", "Фиолетовый"),
                    ("pink", "Розовый"),
                    ("brown", "Коричневый"),
                    ("gray", "Серый"),
                    ("teal", "Бирюзовый"),
                ],
                default="red",
                help_text="В соответствии с техпаспортом",
                max_length=15,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 3, 9, 13, 1, 19, 213772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="itemforcar",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 3, 9, 13, 1, 19, 214771, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="itemformotorcycle",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 3, 9, 13, 1, 19, 214771, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="motocycle",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Красный"),
                    ("blue", "Синий"),
                    ("green", "Зеленый"),
                    ("yellow", "Желтый"),
                    ("orange", "Ораньжевый"),
                    ("purple", "Фиолетовый"),
                    ("pink", "Розовый"),
                    ("brown", "Коричневый"),
                    ("gray", "Серый"),
                    ("teal", "Бирюзовый"),
                ],
                default="red",
                help_text="В соответствии с техпаспортом",
                max_length=15,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="motocycle",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 3, 9, 13, 1, 19, 213772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="guarantee",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 3, 9, 13, 1, 19, 215771, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Гарантийный срок",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="guarantee_period",
            field=models.SmallIntegerField(
                choices=[
                    (6, "6 месяцев"),
                    (12, "12 месяцев"),
                    (24, "2 года"),
                    (36, "3 года"),
                    (60, "5 лет"),
                ],
                default=12,
                verbose_name="Гарантийный период",
            ),
        ),
    ]
