# Generated by Django 4.2.9 on 2024-03-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0007_alter_car_guarantee_alter_itemforcar_guarantee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_django",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_django",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
