cars_brand_models = {
    "Toyota": ["Camry", "Corolla", "RAV4", "Highlander", "Tacoma", "Sienna", "Prius", "C-HR", "4Runner",
               "Land Cruiser"],
    "Volkswagen": ["Golf", "Passat", "Tiguan", "Jetta", "Atlas", "Arteon", "Golf GTI", "Touareg", "ID.4", "T-Cross"],
    "Ford": ["F-150", "Mustang", "Escape", "Explorer", "Ranger", "Edge", "Fusion", "Focus", "Expedition", "Bronco"],
    "Honda": ["Civic", "Accord", "CR-V", "Pilot", "Odyssey", "HR-V", "Ridgeline", "Passport", "Crosstour", "Fit"],
    "Chevrolet": ["Silverado", "Equinox", "Tahoe", "Camaro", "Traverse", "Malibu", "Suburban", "Impala", "Blazer",
                  "Spark"],
    "Nissan": ["Altima", "Rogue", "Sentra", "Pathfinder", "Maxima", "Murano", "Frontier", "Titan", "Armada", "Leaf"],
    "BMW": ["3 Series", "5 Series", "X3", "X5", "7 Series", "X1", "X7", "4 Series", "2 Series", "i3"],
    "Mercedes-Benz": ["C-Class", "E-Class", "GLC", "GLE", "A-Class", "S-Class", "GLA", "GLB", "CLA", "GLS"],
    "Audi": ["A4", "Q5", "A3", "Q7", "A6", "Q3", "A5", "Q8", "TT", "e-tron"],
    "Hyundai": ["Elantra", "Tucson", "Sonata", "Santa Fe", "Kona", "Palisade", "Veloster", "Accent", "Venue", "IONIQ"]
}
motors_brand_models = {
    'Honda': ['Honda CB Shine', 'Honda Activa', 'Honda CBR 250RR', 'Honda CRF 250L', 'Honda Rebel 500',
              'Honda Africa Twin', 'Honda CB650R', 'Honda CB1000R', 'Honda Gold Wing', 'Honda Fireblade (CBR1000RR)'],
    'Yamaha': ['Yamaha YZF-R15', 'Yamaha MT-15', 'Yamaha FZ-S', 'Yamaha FZ25', 'Yamaha R3', 'Yamaha FZ16', 'Yamaha R1',
               'Yamaha XTZ 125', 'Yamaha XSR155', 'Yamaha Tracer 900'],
    'Suzuki': ['Suzuki Hayabusa', 'Suzuki Gixxer SF', 'Suzuki Intruder', 'Suzuki V-Strom 650', 'Suzuki GSX-S750',
               'Suzuki Access 125', 'Suzuki Burgman Street', 'Suzuki RM-Z450', 'Suzuki DR-Z400S', 'Suzuki SV650'],
    'Kawasaki': ['Kawasaki Ninja 300', 'Kawasaki Z650', 'Kawasaki Versys 650', 'Kawasaki Vulcan S',
                 'Kawasaki Ninja ZX-10R', 'Kawasaki KLX 140G', 'Kawasaki W800', 'Kawasaki Z900RS', 'Kawasaki KX450',
                 'Kawasaki Z400'],
    'Harley-Davidson': ['Harley-Davidson Street 750', 'Harley-Davidson Iron 883', 'Harley-Davidson Fat Boy',
                        'Harley-Davidson Road Glide', 'Harley-Davidson Sportster 1200', 'Harley-Davidson Softail Slim',
                        'Harley-Davidson Electra Glide', 'Harley-Davidson Low Rider', 'Harley-Davidson Breakout',
                        'Harley-Davidson LiveWire (Electric)'],
    'Ducati': ['Ducati Panigale V4', 'Ducati Monster 821', 'Ducati Scrambler', 'Ducati Diavel',
               'Ducati Multistrada 950', 'Ducati Hypermotard', 'Ducati SuperSport', 'Ducati Streetfighter V4',
               'Ducati 1299 Panigale', 'Ducati XDiavel'],
    'BMW Motorrad': ['BMW S 1000 RR', 'BMW R 1250 GS', 'BMW F 850 GS', 'BMW G 310 GS', 'BMW R nineT', 'BMW K 1600 GTL',
                     'BMW S 1000 XR', 'BMW F 900 R', 'BMW R 18', 'BMW G 310 R']}

services_title = ['Замена масла', 'Смена резины с летней на зимнюю', 'Смена резины с зимней на летнюю',
                  'Замена масла и фильтра масла',
                  'Замена свечей зажигания',
                  'Замена воздушного фильтра',
                  'Замена топливного фильтра',
                  'Балансировка колес',
                  'Развал-схождение',
                  'Замена тормозных колодок и дисков',
                  'Замена антифриза',
                  'Замена ремня ГРМ',
                  'Диагностика и ремонт электрики',
                  'Замена амортизаторов',
                  'Замена рулевых тяг и наконечников',
                  'Замена ремня кондиционера',
                  'Чистка форсунок топливной системы',
                  'Замена рулевой рейки',
                  'Замена трансмиссионного масла',
                  'Замена ремня генератора',
                  'Замена подшипников колес',
                  'Чистка и обслуживание системы кондиционирования',
                  'Замена топливного насоса',
                  ]
