# Generated by Django 4.2.9 on 2024-02-19 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Buyer",
        ),
    ]
